# Generated by Django 3.2.19 on 2023-06-03 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20, unique=20)),
                ('password', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=20)),
                ('motto', models.CharField(max_length=50)),
            ],
        ),
    ]
