# Generated by Django 3.2.19 on 2023-06-03 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='coin',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='dwarf',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='mana',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='mineral',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
