# Generated by Django 3.2.15 on 2023-06-03 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20230603_1012'),
    ]

    operations = [
        migrations.CreateModel(
            name='DwarfFirstname',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DwarfSecondname',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('secondname', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameModel(
            old_name='User',
            new_name='Player',
        ),
        migrations.CreateModel(
            name='Dwarf',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('strength', models.IntegerField()),
                ('dexterity', models.IntegerField()),
                ('constitution', models.IntegerField()),
                ('intelligence', models.IntegerField()),
                ('wisdom', models.IntegerField()),
                ('charisma', models.IntegerField()),
                ('firstname', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.dwarffirstname')),
                ('secondname', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.dwarfsecondname')),
            ],
        ),
        migrations.CreateModel(
            name='Employ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.IntegerField(default=0)),
                ('dwarf', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.dwarf')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.player')),
            ],
            options={
                'unique_together': {('player', 'dwarf')},
            },
        ),
    ]
