# Generated by Django 3.2.15 on 2023-06-03 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20230603_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='dwarf',
            name='sex',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='dwarffirstname',
            name='firstname',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='dwarfsecondname',
            name='secondname',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
