# Generated by Django 3.2.15 on 2023-06-03 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20230603_2323'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employ',
            new_name='Employment',
        ),
    ]
