# Generated by Django 3.2.15 on 2023-06-03 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_employ_employment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='dwarf',
        ),
        migrations.AddField(
            model_name='dwarf',
            name='job',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dwarf',
            name='player',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='main.player'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Employment',
        ),
    ]
