# Generated by Django 3.2.15 on 2023-06-04 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20230603_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='resource_refresh_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='resource_refresh_count_max',
            field=models.IntegerField(default=5),
        ),
    ]
