# Generated by Django 3.2.15 on 2023-06-04 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20230604_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='resource_refresh_count_max',
            field=models.IntegerField(default=10),
        ),
    ]
