# Generated by Django 3.2.15 on 2023-06-04 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20230604_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='story_process',
            field=models.IntegerField(default=0),
        ),
    ]
