# Generated by Django 3.2.15 on 2023-06-14 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_player_story_process'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='resource_refresh_count',
        ),
        migrations.RemoveField(
            model_name='player',
            name='resource_refresh_count_max',
        ),
        migrations.AddField(
            model_name='player',
            name='coin_harvest_base',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='player',
            name='coin_harvest_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='coin_harvest_interval',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='player',
            name='coin_harvest_multiple',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='player',
            name='dwarf_harvest_base',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='dwarf_harvest_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='dwarf_harvest_interval',
            field=models.IntegerField(default=600),
        ),
        migrations.AddField(
            model_name='player',
            name='employ_dwarf_salary',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='player',
            name='mana_harvest_base',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='mana_harvest_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='mana_harvest_interval',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='player',
            name='mana_harvest_multiple',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='player',
            name='mineral_harvest_base',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='mineral_harvest_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='mineral_harvest_interval',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='player',
            name='mineral_harvest_multiple',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('effect_describe', models.CharField(default='', max_length=200)),
                ('background_describe', models.CharField(default='', max_length=200)),
                ('mana_cost', models.IntegerField(default=0)),
                ('coin_cost', models.IntegerField(default=0)),
                ('mineral_cost', models.IntegerField(default=0)),
                ('idle_dwarf_cost', models.IntegerField(default=0)),
                ('miner_cost', models.IntegerField(default=0)),
                ('merchant_cost', models.IntegerField(default=0)),
                ('soldier_cost', models.IntegerField(default=0)),
                ('mana_harvest_base_increase', models.IntegerField(default=0)),
                ('mana_harvest_multiple_increase', models.IntegerField(default=0)),
                ('mana_harvest_interval_decrease', models.IntegerField(default=0)),
                ('coin_harvest_base_increase', models.IntegerField(default=0)),
                ('coin_harvest_multiple_increase', models.IntegerField(default=0)),
                ('coin_harvest_interval_decrease', models.IntegerField(default=0)),
                ('mineral_harvest_base_increase', models.IntegerField(default=0)),
                ('mineral_harvest_multiple_increase', models.IntegerField(default=0)),
                ('mineral_harvest_interval_decrease', models.IntegerField(default=0)),
                ('dwarf_harvest_base_increase', models.IntegerField(default=0)),
                ('dwarf_harvest_multiple_increase', models.IntegerField(default=0)),
                ('dwarf_harvest_interval_decrease', models.IntegerField(default=0)),
                ('employ_dwarf_price_decrease', models.IntegerField(default=0)),
                ('employ_dwarf_salary_decrease', models.FloatField(default=0)),
                ('tag', models.CharField(default='', max_length=20)),
                ('precondition', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.skill')),
            ],
        ),
    ]
