# Generated by Django 3.2.19 on 2023-06-14 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_player_story_process'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followers', to='main.Player'),
        ),
    ]
