# Generated by Django 3.2.15 on 2023-06-14 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20230614_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='coin_harvest_multiple',
            field=models.IntegerField(default=2),
        ),
    ]
