# Generated by Django 3.2.15 on 2023-06-14 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_player_coin_harvest_multiple'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillStudy',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.player')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.skill')),
            ],
        ),
    ]
