# Generated by Django 3.2.15 on 2023-06-14 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_skill_precondition'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SkillStudy',
            new_name='SkillLearn',
        ),
    ]
