# Generated by Django 3.2.15 on 2023-06-14 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_rename_skillstudy_skilllearn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='dwarf_harvest_multiple_increase',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='idle_dwarf_cost',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='merchant_cost',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='miner_cost',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='soldier_cost',
        ),
        migrations.AddField(
            model_name='skill',
            name='dwarf_limit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='skill',
            name='idle_limit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='skill',
            name='merchant_limit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='skill',
            name='miner_limit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='skill',
            name='soldier_limit',
            field=models.IntegerField(default=0),
        ),
    ]
