# Generated by Django 3.2.15 on 2023-06-14 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20230615_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='motto',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='title',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
