# Generated by Django 3.2.15 on 2023-06-14 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20230615_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='employ_dwarf_salary',
            field=models.FloatField(default=0.25),
        ),
    ]
