# Generated by Django 3.2.15 on 2023-06-14 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_player_following'),
        ('main', '0022_alter_player_employ_dwarf_salary'),
    ]

    operations = [
    ]
