# Generated by Django 3.2.15 on 2023-06-14 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_merge_20230615_0140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='idle_limit',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='merchant_limit',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='miner_limit',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='soldier_limit',
        ),
    ]
