# Generated by Django 3.2.15 on 2023-06-15 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20230615_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='employ_dwarf_salary',
            field=models.FloatField(default=0.34),
        ),
    ]
